### PR TITLE
First CS / Language Review

### PR DESCRIPTION
**Pull request by zero-24**
@wnnz34 @icampus , @Mpompejus , @G-Lu

Can you have a look here and merge if ok. I have not fully tested that changes but they should work and improve the code and language strings.

Let me know if you need any more infos about the changes. (mostly doc block, language strings and code style)

Thanks :smiley:

### CODE REVIEW

**Comment by zero-24** [comment]
PR is: https://github.com/joomla/joomla-cms/pull/8201

**Comment by wnnz34** [comment]
@zero-24  I need more infos about the Changes like if it is working , when the user does not enter an url or path folder (we schould have a response from joomla to tell the uer to enter an url or path folder) same for uploading a (zip) package. when the user does not uploading a package , joomla has to response.

**Comment by wnnz34** [comment]
@zero-24 Did you remove the injection in php file ? so that Js can stranslate the Key to response when the user does not enter any package location, url or folder path ?

**Comment by wnnz34** [comment]
Hello @zero-24 something went wrong .. because there is a checks failure After the Merge in 
PR: joomla#8201. i don't know what is  wrong.

**Comment by zero-24** [comment]
Hmm i have broken some CS rules. I'm going to fix them now. Give me a bit time for a new PR

**Comment by zero-24** [comment]
@wnnz34 can you have a look here: https://github.com/wnnz34/joomla-cms/pull/2

**Pull request merged**
